### ISSUE TITLE
Which param is the final heart rate?

### ISSUE THREAD

**Issue by iluvrachel** [Nuzhny007/HeartRateMeasure#1]
I am learning your codes and they are very good and useful. 
But I still don't know which param is the **final heart rate**?
There are too much number an I don't figure their exact meaning.
Sincerely looking forward to your reply.It will help me a lot.

**Comment by Nuzhny007** [comment]
Hi!
This library is a part of the unwritten Phd dissertation and now isn't final static thing.
Now all probability values of the heart rate contains the GaussMixture class. And most probability value you can get with sp.GetFreq(): https://github.com/Nuzhny007/HeartRateMeasure/blob/master/main.cpp#L281
