### ISSUE TITLE
I dont understand the output "minFreq, maxFreq, currFreq, signalProcessorMoving.GetFreq()" ?

### ISSUE THREAD

**Issue by abdinf** [Nuzhny007/HeartRateMeasure#2]
how to extract the BPM ? i get values around (0.7,200,11,13)

**Comment by Nuzhny007** [comment]
https://github.com/Nuzhny007/HeartRateMeasure/issues/1

**Comment by abdallahinf** [comment]
sorry but still, the sp.GetFreq is giving me values between (9 and 15) which are too high (i.e., BPM=sp.GetFreq*60) , i am computing it correctly ?
