### ISSUE TITLE
 How to Get Heart Rate

### ISSUE THREAD

**Issue by jianghongsun** [Nuzhny007/HeartRateMeasure#3]
Thank you for your sharing. I configure dependencies under Visual Studio 2017. But I don't know how to input parameters to get the heart rate?Can you give me some advice? 
Looking forward to your reply！ Thank you!

**Comment by Nuzhny007** [comment]
Hi!
The final value signalProcessorColor.GetFreq(): https://github.com/Nuzhny007/HeartRateMeasure/blob/master/main.cpp#L377

**Comment by jianghongsun** [comment]
Hi!
Thank you for your answer. Can you give us the running environment and related dependencies of your code and the final implementation results?

**Comment by Nuzhny007** [comment]
I made some updates in project and Readme. If you need something else - You are welcome.

**Comment by jianghongsun** [comment]
Thank you very much for you reply!
