### ISSUE TITLE
clone windows version needs password?

### ISSUE THREAD

**Issue by sjz123321** [Nuzhny007/HeartRateMeasure#7]
I trying to clone https://nuzhny007@bitbucket.org/nuzhny007/beatmagnifier.git But I don't know the password. could you give me the password?

**Comment by Nuzhny007** [comment]
It's joke? I can not give you my password.
And version on bitbucket is the same.

**Comment by sjz123321** [comment]
I am sorry if I upset you. I encountered some error messages in compilation.so I thought these two project maybe different.

**Comment by Nuzhny007** [comment]
Whats errors? I can help you
