### ISSUE TITLE
Спросите о принципе оценки спектра мощности

### ISSUE THREAD

**Issue by Z-Xiong** [Nuzhny007/HeartRateMeasure#8]
https://github.com/Nuzhny007/HeartRateMeasure/blob/adf531bb67ba80bfe05edc9346e0ee66eec99e01/src/beat_calc/signal_vpg/pulseprocessor.cpp#L121
Я не совсем понимаю принцип вашей оценки спектра мощности, на каком методе она основана? Есть ли у вас какие-либо ссылки или документы?

**Comment by Nuzhny007** [comment]
Этот метод я взял для сравнения из библиотеки https://github.com/pi-null-mezon/vpglib
Автор Александр Таранов писал кандидатскую на эту тему, наверное доступны его статьи и автореферат, можно поискать на той же elibrary. Если не получится найти первоисточник, то могу помочь.

**Comment by Z-Xiong** [comment]
Thank you very much for your reply, I have also raised a question under the link you provided. As for the doctoral dissertation you mentioned, because I don't speak Russian, is the dissertation in English?

**Comment by Z-Xiong** [comment]
Are you talking about these three papers? i found it from here https://github.com/pi-null-mezon/QPULSECAPTURE/wiki
1. А. А. Таранов, И. Н. Спиридонов, «Регистрация фотоплетизмограммы и измерение частоты артериального пульса при помощи веб камеры», Биомедицинская радиоэлектроника 10, 71-80 (2014);
3. А. А. Таранов, А.В. Колпаков, И.Н. Спиридонов, «Визуализация подкожного кровеносного русла в ближней инфракрасной области спектра», Медицинская техника 4, 1-5 (2011);
5. A. A. Taranov, A.V. Kolpakov, I.N. Spiridonov, «Near infrared imaging of subcutaneous blood vasculature», Biomedical Engineering 4(45), 115-118 (2011);

**Comment by Nuzhny007** [comment]
> is the dissertation in English?

No, only in russian. But you can ask about it Alex himself.

**Comment by Z-Xiong** [comment]
Thanks a lot. I will close the issue.
